# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
sudo: required
cache: packages

apt_packages:
  - libxml2-dev

services:
  - docker

before_install:
  # mainly for installing sf (which requires units/rgeos/rgdal)
  #- sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  #- sudo apt-get --yes --force-yes update -qq
  #- sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  #- Rscript -e 'update.packages(ask = FALSE)'
  # docker images for integration tests
  #- docker pull kartoza/postgis
  #- docker run -d --name="postgis" kartoza/postgis
  #- docker pull oscarfonts/geoserver
  #- docker run --link postgis:postgis --name geoserver -d -p 8080:8080 oscarfonts/geoserver
  #- docker run --name geonetwork -d -p 8282:8080 pobsteta/docker-geonetwork:3.0.5

r:
  - oldrel
  - release
  #- devel

r_github_packages:
  - hadley/devtools

r_packages:
  - jsonlite
  - testthat
  - covr

r_check_args: --as-cran

after_script:
 - ./travis-tool.sh dump_logs
 
after_success:
 - Rscript -e 'library(covr); codecov()'

notifications:
  email:
    on_success: change
    on_failure: change